### PR TITLE
Rework login flow to ensure accessToken is valid at each launch

### PR DESCRIPTION
**Pull request by lukecyca**
A number of improvements:
* Login flow looks a bit better (fewer janky screens flashing)
* Gracefully handles if a user declines the warning, and lets them try again
* If the app has an accessToken from a previous launch, it gets validated at launch. If it isn't valid, the user is kicked back to login again.

### CODE REVIEW

**Comment by coryheath** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@mycoralhealthdev/mycoral-patient-login-rework

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Review by grcevski — APPROVED** [review]
Looks good to me! LGTM.

**Comment by grcevski** [comment]
I think I must've touched LoginScreen and this branch now has conflict. I think I just put our logo just before the button, no logic changes.

**Comment by coryheath** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@mycoralhealthdev/mycoral-patient-login-rework

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Pull request merged**
